# Printing flags
USE_PRINT_BUFFER = 0
PRINT_LEVEL = 3

GMM_CONFIGS :=

# Enable RW hint
#GMM_CONFIGS += -DGMM_RW

# Copy on write
#GMM_CONFIGS += -DGMM_CONFIG_COW

# Use the radical version of HtoD?
#GMM_CONFIGS += -DGMM_CONFIG_HTOD_RADICAL

# Replacement policy
GMM_CONFIGS += -DGMM_REPLACEMENT_LRU
#GMM_CONFIGS += -DGMM_REPLACEMENT_LFU
#GMM_CONFIGS += -DGMM_REPLACEMENT_RANDOM
